name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check_and_export:
    runs-on: ubuntu-22.04
    container: 
      image: ghcr.io/kicad/kicad:8.0
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: src
          fetch-depth: 0

      - name: ERC
        working-directory: src
        run: |
          HW_REV=$(git describe --tags)
          kicad-cli sch erc SerialTempSens.kicad_sch -o SerialTempSens_ERC_${HW_REV}

      - name: DRC
        working-directory: src
        run: |
          HW_REV=$(git describe --tags)
          kicad-cli pcb drc SerialTempSens.kicad_pcb -o SerialTempSens_DRC_${HW_REV}

      - name: Export outputs
        working-directory: src
        run: |
          sudo apt update
          sudo apt install -y ghostscript
          HW_REV=$(git describe --tags)
          kicad-cli sch export pdf SerialTempSens.kicad_sch -o SerialTempSens_Schematic_${HW_REV}.pdf
          kicad-cli sch export bom --fields 'Reference,Value,${QUANTITY}' --exclude-dnp --group-by "Value" SerialTempSens.kicad_sch -o SerialTempSens_Bom_${HW_REV}.pdf
          kicad-cli pcb export pdf -l F.Fab,Edge.Cuts SerialTempSens.kicad_pcb -o top.pdf
          kicad-cli pcb export pdf -l B.Fab,Edge.Cuts --mirror SerialTempSens.kicad_pcb -o bot.pdf
          gs -dBATCH -dNOPAUSE -q -sDEVICE=pdfwrite -dPDFSETTINGS=/prepress -sOutputFile=SerialTempSens_Placement_${HW_REV}.pdf top.pdf bot.pdf
          
      - name: Archive reports
        uses: actions/upload-artifact@v4
        with:
          name: SerialTempSens_reports
          path: |
            SerialTempSens_DRC_*
            SerialTempSens_ERC_*
            
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/v')
        with:
          files: |
            SerialTempSens_Schematic_*.pdf
            SerialTempSens_Placement_*.pdf
            SerialTempSens_Bom_*.csv
